### ISSUE TITLE
lzip version requirement

### ISSUE THREAD

**Issue by pghmcfc** [coppit/grepmail#4]
I tried building grepmail on some old Fedora releases that had an old version (1.1) of lzip, and they failed the grepmail test suite as they were unable to uncompress t/mailboxes/mailarc-1.txt.lz. The next oldest version I was able to try was 1.7, which worked OK. Looking at the lzip ChangeLog, I suspect the version requirement is for version 1.3, which adds support for decompressing "version 1" files. You might want to note this in the README, or better still, check the version before trying the test.

**Comment by coppit** [comment]
Thanks. The "lzip enabled" flag is actually set in the
Mail::Mbox::MessageParser module instead of grepmail. I added a version
check. Note that you'd have to install this new version of the module in
order to "unenable" lzip support. Your currently installed version
erroneously thinks your version of lzip is good enough.
